# Generated by Django 6.0.6 on 2026-06-18 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricingRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Boarding Volume Discount', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Pricing Rule',
                'verbose_name_plural': 'Dynamic Pricing Rules',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('min_bookings', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Loyalty Tier',
                'verbose_name_plural': 'Loyalty Tiers',
                'ordering': ['min_bookings'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 1), ('discount_percentage__lte', 50)), name='loyalty_discount_range')],
            },
        ),
        migrations.CreateModel(
            name='DynamicPricingTier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='promotions.dynamicpricingrule')),
            ],
            options={
                'verbose_name': 'Dynamic Pricing Tier',
                'verbose_name_plural': 'Dynamic Pricing Tiers',
                'ordering': ['min_days'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 50)), name='dp_tier_discount_range'), models.CheckConstraint(condition=models.Q(('min_days__lte', models.F('max_days'))), name='dp_tier_min_lte_max')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('target_categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_services', models.ManyToManyField(blank=True, related_name='promotions', to='services.service')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active', '-start_date'], name='promo_active_start_idx')],
            },
        ),
    ]
